spring.application.name=ticketing-api
logging.level.root=info
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/local
spring.flyway.url=jdbc:postgresql://localhost:5432/postgres
spring.flyway.user=postgres
spring.flyway.password=guanyiping
# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=guanyiping
# JWT ??
jwt.secret="qJz8#4l@V7uTz$A1hKmZ!9rXePgF^2yM"
jwt.expiration-ms=3600000
